#!/usr/bin/python

import os,sys,re
from datetime import datetime


options = { '0':'empty-example','1':'empty-threejs', '2':'empty-aframe', '3':'empty-html', '4':'empty-phaser' }
currentDir = os.listdir("./")
currentDate = datetime.today().strftime("%Y%m%d")
r = re.compile(currentDate + ".")
todaysSketches = filter(r.match,currentDir)

print("What kind of sketch do you want to create today?")
print("(0) for p5.js")
print("(1) for Three.js")
print("(2) for A-Frame")
print("(3) for just HTML")
print("(4) for Phaser.io")
print("");
sketchtype = raw_input(">> ")
if(len(todaysSketches)>=9):
    sketchname = currentDate + str(len(todaysSketches) + 1)
    print( currentDate + "0" + str(len(todaysSketches) + 1))
elif(len(todaysSketches)>0 and len(todaysSketches)<9):
    sketchname = currentDate + "0" + str(len(todaysSketches) + 1)
else:
    sketchname = currentDate + "01"

print(sketchtype)
if sketchtype in options:
    print("Creating sketch: " + sketchname)
    os.system("cp -r ./" + options[sketchtype] + " " + sketchname)
    os.system("$myEditor " + sketchname + "/sketch.js &")
    os.system("http-server ./" + sketchname)
else:
    print("You did not choose one of the possible options.")
    print("Aborting sketch creation.")
